name: "Azure Machine Learning Run Action"
description: "Submit a run to an Azure Machine Learning Workspace with this GitHub Action"
author: "azure/gh-aml"
inputs:
  azure_credentials:
    description: "Paste output of `az ad sp create-for-rbac --name <your-sp-name> --role contributor --scopes /subscriptions/<your-subscriptionId>/resourceGroups/<your-rg> --sdk-auth` as value of secret variable: AZURE_CREDENTIALS"
    required: true
  events_mapfile:
    description: "file where all required event maps are existing"
    required: true
    default: event_subscription.json
  resource_group:
    description: "resource group which is to be used to deploy the function app"
    required: true
    default: "newresource_grp"
  pattoken:
    description: "personal access token"
    required: true
outputs:
  destination_url:
    description: "destination url where event is assigned"
branding:
  icon: "chevron-up"
  color: "blue"
runs:
  using: "docker"
  image: "Dockerfile"
