# Test Actions create an event subscription to a function app
name: create-event-subscription 
on:
  push:

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Check Out Repository
      id: checkout_repository
      uses: actions/checkout@v2

    # Deploys function app and creates an event grid subscription
    - name: create event subscription
      id: azure_eventgridsubscriber
      uses: ./
      with:
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
          provider_type: "Microsoft.MachineLearningServices/workspaces/new11"
          resource_group: "test5"
          events_to_subscribe: |
              Microsoft.MachineLearningServices.RunStatusChanged
              Microsoft.MachineLearningServices.RunCompleted
          pattoken: ${{secrets.PATTOKEN}}
